=== Morphite/EpamPracticeTasks/Practice7/input.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:element name="Beers">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="Beer" type="AbsBeer" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="AbsBeer" abstract="true"/>

    <xsd:complexType name="NonAlcBeer">

        <xsd:complexContent>
            <xsd:extension base="AbsBeer">

                <xsd:sequence>
                    <xsd:element name="Name" type="xsd:string"/>
                    <xsd:element name="Type" type="xsd:string"/>
                    <xsd:element name="Al" type="xsd:boolean" fixed="false"/>
                    <xsd:element name="Manufacturer" type="xsd:string"/>
                    <xsd:sequence>
                        <xsd:element name="Ingredients" type="Ingredients"/>
                    </xsd:sequence>
                    <xsd:element name="Transparency" type="xsd:string"/>
                    <xsd:element name="Filter" type="xsd:boolean"/>
                    <xsd:element name="NutritionalValue" type="xsd:string"/>
                    <xsd:element name="FillChar" type="ContainerChar"/>
                </xsd:sequence>

            </xsd:extension>
        </xsd:complexContent>

    </xsd:complexType>

    <xsd:complexType name="AlcBeer">
        <xsd:complexContent>
            <xsd:extension base="AbsBeer">

                <xsd:sequence>
                    <xsd:element name="Name" type="xsd:string"/>
                    <xsd:element name="Type" type="xsd:string"/>
                    <xsd:element name="Al" type="xsd:boolean" fixed="true"/>
                    <xsd:element name="Manufacturer" type="xsd:string"/>
                    <xsd:sequence>
                        <xsd:element name="Ingredients" type="Ingredients"/>
                    </xsd:sequence>
                    <xsd:element name="alcPercent" type="xsd:string"/>
                    <xsd:element name="Transparency" type="xsd:string"/>
                    <xsd:element name="Filter" type="xsd:boolean"/>
                    <xsd:element name="NutritionalValue" type="xsd:string"/>
                    <xsd:element name="FillChar" type="ContainerChar"/>
                </xsd:sequence>

            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>


    <xsd:complexType name="Ingredients" mixed="true">
        <xsd:sequence>
            <xsd:element name="Name" type="xsd:string" minOccurs="3" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Enumeration">
        <xsd:sequence>
            <xsd:element name="type" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="ContainerChar">
        <xsd:sequence>
            <xsd:element name="volume" type="xsd:string"/>
            <xsd:element name="packageMaterial" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== Morphite/EpamPracticeTasks/Practice7/input.xml
<?xml version="1.0" encoding="UTF-8"?>

<Beers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="input.xsd">

    <Beer xsi:type="NonAlcBeer">
        <Name>Kronenburg Blanc</Name>
        <Type>Blonde</Type>
        <Al>false</Al>
        <Manufacturer>Carlsberg</Manufacturer>
        <Ingredients>
            <Name>Water</Name>
            <Name>Malt</Name>
            <Name>Wheat</Name>
        </Ingredients>
        <Transparency>12</Transparency>
        <Filter>true</Filter>
        <NutritionalValue>147</NutritionalValue>
        <FillChar>
            <volume>0,5</volume>
            <packageMaterial>glass</packageMaterial>
        </FillChar>
    </Beer>

    <Beer xsi:type="AlcBeer">
        <Name>Guiness</Name>
        <Type>Stout</Type>
        <Al>true</Al>
        <Manufacturer>Diageo</Manufacturer>
        <Ingredients>
            <Name>Water</Name>
            <Name>Malt</Name>
            <Name>Wheat</Name>
        </Ingredients>
        <alcPercent>4</alcPercent>
        <Transparency>19</Transparency>
        <Filter>true</Filter>
        <NutritionalValue>132</NutritionalValue>
        <FillChar>
            <volume>0,5</volume>
            <packageMaterial>glass</packageMaterial>
        </FillChar>
    </Beer>

    <Beer xsi:type="AlcBeer">
        <Name>New</Name>
        <Type>Stout</Type>
        <Al>true</Al>
        <Manufacturer>Diageo</Manufacturer>
        <Ingredients>
            <Name>Water</Name>
            <Name>Malt</Name>
            <Name>Wheat</Name>
        </Ingredients>
        <alcPercent>12</alcPercent>
        <Transparency>16</Transparency>
        <Filter>true</Filter>
        <NutritionalValue>203</NutritionalValue>
        <FillChar>
            <volume>0,5</volume>
            <packageMaterial>glass</packageMaterial>
        </FillChar>
    </Beer>

    <Beer xsi:type="AlcBeer">
        <Name>Test</Name>
        <Type>Lager</Type>
        <Al>true</Al>
        <Manufacturer>Diageo</Manufacturer>
        <Ingredients>
            <Name>Water</Name>
            <Name>Malt</Name>
            <Name>Wheat</Name>
        </Ingredients>
        <alcPercent>3</alcPercent>
        <Transparency>11</Transparency>
        <Filter>true</Filter>
        <NutritionalValue>153</NutritionalValue>
        <FillChar>
            <volume>0,5</volume>
            <packageMaterial>glass</packageMaterial>
        </FillChar>
    </Beer>

</Beers>
